[book]
authors = ["Silk Rose", "Cultist_O", "Autumn Meadow", "Epic Acrylic", "XCRunnerS"]
language = "en"
multilingual = false
src = "src"
title = "Resource Pack Guide"

[build]
build-dir = "guide"

[output.html]
default-theme = "l_t"
preferred-dark-theme = "l_t_dark"
additional-css = ["./theme/love-and-tolerance.css", "./theme/love-and-tolerance-highlight.css", "./theme/catppuccin.css", "./theme/catppuccin-highlight.css"]
git-repository-url = "https://github.com/Love-and-Tolerance/Resource-Pack-Guide"