name: Build and Deploy Guide Site

on:
  push:
    branches:
      - deploy

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup
      uses: actions/checkout@v3

    - name: Setup rust
      run: |
        rustup update 1.66.0
        rustup default 1.66.0

    - run: cargo install mdbook oxipng

    - name: Build
      run: ./build-gh-pages.sh

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: deploy
